"""
Fixtures for database introspection integration tests.
"""

from pathlib import Path

import pytest

from tests.integration.helpers.migration_helper import create_versioned_migration


def generate_introspection_test_sql(db_type: str) -> str:
    """
    Generate comprehensive introspection test SQL for the specified database.

    Creates tables with various constraint types, views, sequences (if supported),
    and indexes to test introspection coverage.
    """
    if db_type == "postgresql":
        return """
-- PostgreSQL Test Migration: Comprehensive Schema
CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE orders_id_seq START WITH 100 INCREMENT BY 1 CYCLE;

CREATE TABLE users (
    id INTEGER PRIMARY KEY DEFAULT nextval('users_id_seq'),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    age INTEGER,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_age CHECK (age >= 18 AND age <= 120),
    CONSTRAINT chk_users_email CHECK (email LIKE '%@%'),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    budget NUMERIC(15, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dept_budget CHECK (budget > 0)
);

CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    department_id INTEGER,
    salary NUMERIC(12, 2) NOT NULL,
    hire_date DATE NOT NULL,
    is_manager BOOLEAN DEFAULT false,
    CONSTRAINT fk_emp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT chk_emp_salary CHECK (salary > 0),
    CONSTRAINT chk_emp_hire_date CHECK (hire_date <= CURRENT_DATE)
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY DEFAULT nextval('orders_id_seq'),
    user_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_orders_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'processing', 'completed', 'cancelled'))
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) DEFAULT 0.08,
    price_with_tax NUMERIC(10, 2) GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED,
    CONSTRAINT chk_products_price CHECK (price > 0),
    CONSTRAINT chk_products_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 1)
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_emp_dept_salary ON employees(department_id, salary DESC);

CREATE VIEW active_users AS SELECT id, username, email, age, created_at FROM users WHERE status = 'active';
CREATE VIEW employee_details AS
    SELECT e.id, u.username, u.email, d.name as department_name, e.salary, e.hire_date
    FROM employees e JOIN users u ON e.user_id = u.id LEFT JOIN departments d ON e.department_id = d.id;
CREATE VIEW department_summary AS
    SELECT d.id, d.name, d.budget, COUNT(e.id) as employee_count, AVG(e.salary) as avg_salary
    FROM departments d LEFT JOIN employees e ON e.department_id = d.id GROUP BY d.id, d.name, d.budget;

-- User-Defined Types (NEW)
CREATE TYPE status_enum AS ENUM ('active', 'inactive', 'pending', 'archived');
CREATE TYPE address_type AS (
    street VARCHAR(100),
    city VARCHAR(50),
    zip_code VARCHAR(10)
);
CREATE DOMAIN email_domain AS VARCHAR(255) CHECK (VALUE ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z]{2,}$');

-- Synonyms (NEW) - PostgreSQL doesn't support synonyms, skip

-- Extensions (NEW) - We don't create extensions (requires admin), just test detection
"""
    elif db_type == "mysql":
        return """
-- MySQL Test Migration: Comprehensive Schema
-- Note: MySQL doesn't allow non-deterministic functions in CHECK constraints
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    age INTEGER,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_age CHECK (age >= 18 AND age <= 120),
    CONSTRAINT chk_users_email CHECK (email LIKE '%@%'),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE departments (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    budget DECIMAL(15, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dept_budget CHECK (budget > 0)
);

CREATE TABLE employees (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    department_id INTEGER,
    salary DECIMAL(12, 2) NOT NULL,
    hire_date DATE NOT NULL,
    is_manager BOOLEAN DEFAULT false,
    CONSTRAINT fk_emp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT chk_emp_salary CHECK (salary > 0)
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_orders_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'processing', 'completed', 'cancelled'))
);

CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    tax_rate DECIMAL(5, 4) DEFAULT 0.08,
    price_with_tax DECIMAL(10, 2) GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED,
    CONSTRAINT chk_products_price CHECK (price > 0),
    CONSTRAINT chk_products_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 1)
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_emp_dept_salary ON employees(department_id, salary DESC);

CREATE VIEW active_users AS SELECT id, username, email, age, created_at FROM users WHERE status = 'active';
CREATE VIEW employee_details AS
    SELECT e.id, u.username, u.email, d.name as department_name, e.salary, e.hire_date
    FROM employees e JOIN users u ON e.user_id = u.id LEFT JOIN departments d ON e.department_id = d.id;
CREATE VIEW department_summary AS
    SELECT d.id, d.name, d.budget, COUNT(e.id) as employee_count, AVG(e.salary) as avg_salary
    FROM departments d LEFT JOIN employees e ON e.department_id = d.id GROUP BY d.id, d.name, d.budget;
"""
    elif db_type == "oracle":
        return """
-- Oracle Test Migration: Comprehensive Schema
CREATE SEQUENCE USERS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ORDERS_ID_SEQ START WITH 100 INCREMENT BY 1 MAXVALUE 9999999 CYCLE;

CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL,
    AGE NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_USERS_AGE CHECK (AGE >= 18 AND AGE <= 120),
    CONSTRAINT CHK_USERS_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT CHK_USERS_STATUS CHECK (STATUS IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE DEPARTMENTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    BUDGET NUMBER(15, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_DEPT_BUDGET CHECK (BUDGET > 0)
);

CREATE TABLE EMPLOYEES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    DEPARTMENT_ID NUMBER,
    SALARY NUMBER(12, 2) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    IS_MANAGER NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_EMP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE SET NULL,
    CONSTRAINT CHK_EMP_SALARY CHECK (SALARY > 0)
);

CREATE TABLE ORDERS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT NUMBER(12, 2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_ORDERS_AMOUNT CHECK (TOTAL_AMOUNT >= 0),
    CONSTRAINT CHK_ORDERS_STATUS CHECK (STATUS IN ('pending', 'processing', 'completed', 'cancelled'))
);

CREATE TABLE PRODUCTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    TAX_RATE NUMBER(5, 4) DEFAULT 0.08,
    PRICE_WITH_TAX NUMBER(10, 2) GENERATED ALWAYS AS (PRICE * (1 + TAX_RATE)) VIRTUAL,
    CONSTRAINT CHK_PRODUCTS_PRICE CHECK (PRICE > 0),
    CONSTRAINT CHK_PRODUCTS_TAX_RATE CHECK (TAX_RATE >= 0 AND TAX_RATE <= 1)
);

CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_EMP_DEPT_SALARY ON EMPLOYEES(DEPARTMENT_ID, SALARY DESC);

CREATE VIEW ACTIVE_USERS AS SELECT ID, USERNAME, EMAIL, AGE, CREATED_AT FROM USERS WHERE STATUS = 'active';
CREATE VIEW EMPLOYEE_DETAILS AS
    SELECT E.ID, U.USERNAME, U.EMAIL, D.NAME as DEPARTMENT_NAME, E.SALARY, E.HIRE_DATE
    FROM EMPLOYEES E JOIN USERS U ON E.USER_ID = U.ID LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.ID;
CREATE VIEW DEPARTMENT_SUMMARY AS
    SELECT D.ID, D.NAME, D.BUDGET, COUNT(E.ID) as EMPLOYEE_COUNT, AVG(E.SALARY) as AVG_SALARY
    FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.ID GROUP BY D.ID, D.NAME, D.BUDGET;

-- Synonyms (NEW)
CREATE OR REPLACE SYNONYM EMP_SYN FOR EMPLOYEES;
CREATE OR REPLACE SYNONYM DEPT_SYN FOR DEPARTMENTS;
"""
    elif db_type == "sqlserver":
        return """
-- SQL Server Test Migration: Comprehensive Schema
CREATE SEQUENCE TEST_SCHEMA.users_id_seq START WITH 1 INCREMENT BY 1;
GO
CREATE SEQUENCE TEST_SCHEMA.orders_id_seq START WITH 100 INCREMENT BY 1 MAXVALUE 9999999 CYCLE;
GO

CREATE TABLE TEST_SCHEMA.users (
    id INTEGER PRIMARY KEY DEFAULT NEXT VALUE FOR TEST_SCHEMA.users_id_seq,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    age INTEGER,
    status VARCHAR(20) DEFAULT 'active',
    created_at DATETIME DEFAULT GETDATE(),
    CONSTRAINT chk_users_age CHECK (age >= 18 AND age <= 120),
    CONSTRAINT chk_users_email CHECK (email LIKE '%@%'),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE TEST_SCHEMA.departments (
    id INTEGER IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    budget DECIMAL(15, 2),
    created_at DATETIME DEFAULT GETDATE(),
    CONSTRAINT chk_dept_budget CHECK (budget > 0)
);

CREATE TABLE TEST_SCHEMA.employees (
    id INTEGER IDENTITY(1,1) PRIMARY KEY,
    user_id INTEGER NOT NULL,
    department_id INTEGER,
    salary DECIMAL(12, 2) NOT NULL,
    hire_date DATE NOT NULL,
    is_manager BIT DEFAULT 0,
    CONSTRAINT fk_emp_user FOREIGN KEY (user_id) REFERENCES TEST_SCHEMA.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES TEST_SCHEMA.departments(id) ON DELETE SET NULL,
    CONSTRAINT chk_emp_salary CHECK (salary > 0),
    CONSTRAINT chk_emp_hire_date CHECK (hire_date <= CAST(GETDATE() AS DATE))
);

CREATE TABLE TEST_SCHEMA.orders (
    id INTEGER PRIMARY KEY DEFAULT NEXT VALUE FOR TEST_SCHEMA.orders_id_seq,
    user_id INTEGER NOT NULL,
    order_date DATETIME DEFAULT GETDATE(),
    total_amount DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES TEST_SCHEMA.users(id),
    CONSTRAINT chk_orders_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'processing', 'completed', 'cancelled'))
);

CREATE TABLE TEST_SCHEMA.products (
    id INTEGER IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    tax_rate DECIMAL(5, 4) DEFAULT 0.08,
    price_with_tax AS (price * (1 + tax_rate)) PERSISTED,
    CONSTRAINT chk_products_price CHECK (price > 0),
    CONSTRAINT chk_products_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 1)
);

CREATE INDEX idx_users_email ON TEST_SCHEMA.users(email);
CREATE INDEX idx_emp_dept_salary ON TEST_SCHEMA.employees(department_id, salary DESC);

CREATE VIEW TEST_SCHEMA.active_users AS SELECT id, username, email, age, created_at FROM TEST_SCHEMA.users WHERE status = 'active';
GO
CREATE VIEW TEST_SCHEMA.employee_details AS
    SELECT e.id, u.username, u.email, d.name as department_name, e.salary, e.hire_date
    FROM TEST_SCHEMA.employees e JOIN TEST_SCHEMA.users u ON e.user_id = u.id LEFT JOIN TEST_SCHEMA.departments d ON e.department_id = d.id;
GO
CREATE VIEW TEST_SCHEMA.department_summary AS
    SELECT d.id, d.name, d.budget, COUNT(e.id) as employee_count, AVG(e.salary) as avg_salary
    FROM TEST_SCHEMA.departments d LEFT JOIN TEST_SCHEMA.employees e ON e.department_id = d.id GROUP BY d.id, d.name, d.budget;
GO

-- Synonyms (NEW)
CREATE SYNONYM TEST_SCHEMA.emp_syn FOR TEST_SCHEMA.employees;
GO
CREATE SYNONYM TEST_SCHEMA.dept_syn FOR TEST_SCHEMA.departments;
GO
"""
    elif db_type == "db2":
        return """
-- DB2 Test Migration: Comprehensive Schema
-- Note: DB2 doesn't support DEFAULT NEXT VALUE FOR in column definition with PRIMARY KEY
-- Using GENERATED BY DEFAULT AS IDENTITY and standalone sequences for testing both

CREATE SEQUENCE USERS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ORDERS_ID_SEQ START WITH 100 INCREMENT BY 1 CYCLE;

CREATE TABLE USERS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL,
    AGE INTEGER,
    STATUS VARCHAR(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT CHK_USERS_AGE CHECK (AGE >= 18 AND AGE <= 120),
    CONSTRAINT CHK_USERS_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT CHK_USERS_STATUS CHECK (STATUS IN ('active', 'inactive', 'suspended'))
);

CREATE TABLE DEPARTMENTS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BUDGET DECIMAL(15, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT CHK_DEPT_BUDGET CHECK (BUDGET > 0)
);

CREATE TABLE EMPLOYEES (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    DEPARTMENT_ID INTEGER,
    SALARY DECIMAL(12, 2) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    IS_MANAGER SMALLINT DEFAULT 0,
    CONSTRAINT FK_EMP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE SET NULL,
    CONSTRAINT CHK_EMP_SALARY CHECK (SALARY > 0)
);

CREATE TABLE ORDERS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_ORDERS_AMOUNT CHECK (TOTAL_AMOUNT >= 0),
    CONSTRAINT CHK_ORDERS_STATUS CHECK (STATUS IN ('pending', 'processing', 'completed', 'cancelled'))
);

CREATE TABLE PRODUCTS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    TAX_RATE DECIMAL(5, 4) DEFAULT 0.08,
    PRICE_WITH_TAX DECIMAL(10, 2) GENERATED ALWAYS AS (PRICE * (1 + TAX_RATE)),
    CONSTRAINT CHK_PRODUCTS_PRICE CHECK (PRICE > 0),
    CONSTRAINT CHK_PRODUCTS_TAX_RATE CHECK (TAX_RATE >= 0 AND TAX_RATE <= 1)
);

CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_EMP_DEPT_SALARY ON EMPLOYEES(DEPARTMENT_ID, SALARY DESC);

CREATE VIEW ACTIVE_USERS AS SELECT ID, USERNAME, EMAIL, AGE, CREATED_AT FROM USERS WHERE STATUS = 'active';
CREATE VIEW EMPLOYEE_DETAILS AS
    SELECT E.ID, U.USERNAME, U.EMAIL, D.NAME as DEPARTMENT_NAME, E.SALARY, E.HIRE_DATE
    FROM EMPLOYEES E JOIN USERS U ON E.USER_ID = U.ID LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.ID;
CREATE VIEW DEPARTMENT_SUMMARY AS
    SELECT D.ID, D.NAME, D.BUDGET, COUNT(E.ID) as EMPLOYEE_COUNT, AVG(E.SALARY) as AVG_SALARY
    FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.ID GROUP BY D.ID, D.NAME, D.BUDGET;

-- Synonyms (NEW) - DB2 uses ALIAS instead of SYNONYM
CREATE ALIAS EMP_ALIAS FOR EMPLOYEES;
CREATE ALIAS DEPT_ALIAS FOR DEPARTMENTS;
"""
    else:
        pytest.skip(f"Introspection test SQL not implemented for {db_type}")


@pytest.fixture
def introspection_migrations(tmp_path, db_container):
    """
    Generate introspection test migrations dynamically.

    Creates comprehensive test schema with tables, constraints, views,
    sequences (if supported), and indexes for testing introspection.
    """
    db_type = db_container["type"]

    # Create migrations directory
    migrations_dir = tmp_path / "introspection_migrations"
    migrations_dir.mkdir(parents=True, exist_ok=True)

    # Generate SQL for the database type
    sql = generate_introspection_test_sql(db_type)

    # Create migration file
    create_versioned_migration(migrations_dir, "001", "create_test_schema", sql)

    return migrations_dir
