"""Shared utilities for comparison operations.

This module provides utility functions used across multiple comparators.
"""

import logging
import re
from typing import TYPE_CHECKING, Any, List, Optional

_logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from sqlglot import exp


def is_system_generated_constraint_name(name: str) -> bool:
    """Check if constraint name is system-generated by the database.

    System-generated names should be ignored when matching constraints,
    as they vary between database instances.

    Args:
        name: Constraint name to check

    Returns:
        True if the name appears to be system-generated

    Examples:
        Oracle: SYS_C0013220 -> True
        SQL Server: PK__users__3213E83F -> True
        PostgreSQL: tablename_pkey, tablename_columnname_key -> True
        User-defined: pk_users_id -> False
    """
    if not name:
        return False

    name_upper = name.upper()
    name_lower = name.lower()

    # Oracle: SYS_C followed by numbers
    if name_upper.startswith("SYS_C"):
        # Check if rest is numeric
        suffix = name_upper[5:]
        if suffix and suffix.isdigit():
            return True

    # SQL Server auto-generated: PK__TableName__Hash or FK__TableName__Hash
    if "__" in name_upper and (name_upper.startswith("PK__") or name_upper.startswith("FK__")):
        return True

    # PostgreSQL auto-generated patterns:
    # - tablename_pkey (primary key) - always auto-generated
    # - tablename_columnname_key (unique) - pattern: contains underscore before _key
    # - tablename_columnname_fkey (foreign key) - always auto-generated
    # - tablename_columnname_check (check constraint) - pattern: contains underscore before _check
    # - unnamed_N (used internally by some tools)
    if name_lower.startswith("unnamed_"):
        return True

    # _pkey is always auto-generated by PostgreSQL for primary keys
    if name_lower.endswith("_pkey"):
        return True

    # _fkey is always auto-generated by PostgreSQL for foreign keys
    if name_lower.endswith("_fkey"):
        return True

    # For _key and _check, match if the name follows PostgreSQL's pattern:
    # tablename_columnname_key (at least 1 underscore in prefix + _key suffix)
    # PostgreSQL generates names with the pattern tablename_columnname_key where both
    # tablename and columnname can contain underscores themselves.
    # We can't rely solely on underscore count since column names may contain underscores.
    # Instead, we check for at least one underscore (to exclude single-word names like "apikey")
    # and exclude keywords that strongly suggest user-defined names.
    if name_lower.endswith("_key"):
        prefix = name_lower[:-4]  # Everything before "_key"
        # PostgreSQL pattern: tablename_columnname_key (has at least 1 underscore in prefix)
        # Single-word prefixes (0 underscores) are definitely user-defined (e.g., "apikey")
        if "_" not in prefix:
            return False
        # Exclude only keywords that strongly suggest user-defined names
        # (not table/column names, as those are part of legitimate auto-generated names)
        user_defined_keywords = [
            "api",  # e.g., "my_api_key" (but "users_api_key" would be auto-generated)
            "primary",  # e.g., "primary_key_override"
            "foreign",  # e.g., "foreign_key_constraint"
            "unique",  # e.g., "unique_key_constraint"
            "override",  # e.g., "override_key"
            "constraint",  # e.g., "constraint_key"
        ]
        # Check if prefix STARTS with or is exactly one of these keywords
        # OR if prefix contains these keywords as complete words (delimited by underscores)
        # This catches "my_api_key" (prefix "my_api" contains "api" as a word)
        # while allowing "users_api_key" (prefix "users_api" - "api" is a column name, so auto-generated)
        prefix_lower = prefix.lower()
        # Check if prefix starts with keyword
        if any(
            prefix_lower == keyword or prefix_lower.startswith(f"{keyword}_")
            for keyword in user_defined_keywords
        ):
            return False
        # Check if prefix contains keyword as a complete word (delimited by underscores or at boundaries)
        # Use word boundaries to match complete words only
        for keyword in user_defined_keywords:
            # Match keyword as a complete word (delimited by underscores or at start/end)
            # Pattern: (^|_)keyword(_|$) - keyword at start, or after underscore, or before underscore, or at end
            pattern = rf"(^|_){re.escape(keyword)}(_|$)"
            if re.search(pattern, prefix_lower):
                # If keyword appears early in prefix (first 2 parts), likely user-defined
                # This catches "my_api" but not "users_api" (since "api" is the second part in both,
                # but "my" suggests user-defined while "users" suggests table name)
                parts = prefix_lower.split("_")
                keyword_index = None
                for i, part in enumerate(parts):
                    if part == keyword:
                        keyword_index = i
                        break
                # If keyword is in first 2 parts and prefix doesn't look like tablename_columnname,
                # it's likely user-defined
                if keyword_index is not None and keyword_index < 2:
                    # Additional check: if the part before keyword is a common word (not a table name),
                    # it's likely user-defined
                    if keyword_index > 0:
                        before_keyword = parts[keyword_index - 1]
                        # Common words that suggest user-defined (not table names)
                        common_user_words = ["my", "our", "the", "a", "an", "this", "that"]
                        if before_keyword in common_user_words:
                            return False
                    else:
                        # Keyword is the first part, definitely user-defined
                        return False
        # If prefix doesn't start with excluded keywords, likely auto-generated
        return True

    if name_lower.endswith("_check"):
        prefix = name_lower[:-6]  # Everything before "_check"
        # Single-word prefixes (0 underscores) are definitely user-defined (e.g., "check")
        if "_" not in prefix:
            return False
        # Exclude only keywords that strongly suggest user-defined names
        user_defined_keywords = [
            "health",  # e.g., "health_check" (but "users_health_check" would be auto-generated)
            "data",  # e.g., "data_check_validation"
            "validation",  # e.g., "validation_check"
            "override",  # e.g., "override_check"
        ]
        # Check if prefix STARTS with or is exactly one of these keywords
        prefix_lower = prefix.lower()
        if any(
            prefix_lower == keyword or prefix_lower.startswith(f"{keyword}_")
            for keyword in user_defined_keywords
        ):
            return False
        # If prefix doesn't start with excluded keywords, likely auto-generated
        return True

    # MySQL auto-generated: Often just the column name for single-column constraints
    # We can't reliably detect these, so we don't mark them as system-generated

    return False


def extract_base_identity_type(data_type: str, dialect: str) -> str:
    """Extract base data type from identity column definition.

    Identity columns can be defined with various syntax:
    - Oracle: NUMBER GENERATED ALWAYS AS IDENTITY
    - PostgreSQL: SERIAL, BIGSERIAL
    - SQL Server: INT IDENTITY(1,1)
    - MySQL: INT AUTO_INCREMENT

    This function extracts just the base type for comparison.

    Args:
        data_type: Full data type string
        dialect: Database dialect

    Returns:
        Base data type without identity keywords
    """
    if not data_type:
        return "" if data_type is None else data_type

    # Convert to string if not already (handles cases where data_type might be an int).
    # data_type here is a SQL column type (VARCHAR, INT, ...), not a MigrationType.
    if not isinstance(data_type, str):
        data_type = str(data_type)  # lint: allow-enum-str

    data_type_upper = data_type.upper().strip()

    # PostgreSQL SERIAL types map to INTEGER/BIGINT
    # Check longer variants first to avoid substring matches (BIGSERIAL contains SERIAL)
    from db.provider_registry import ProviderRegistry

    if ProviderRegistry.get_quirks(dialect).serial_types_alias_integer:
        if data_type_upper == "BIGSERIAL" or data_type_upper.startswith("BIGSERIAL"):
            return "BIGINT"
        if data_type_upper == "SMALLSERIAL" or data_type_upper.startswith("SMALLSERIAL"):
            return "SMALLINT"
        if data_type_upper == "SERIAL" or data_type_upper.startswith("SERIAL"):
            return "INTEGER"

    # Remove identity-related keywords for other dialects
    # Remove IDENTITY(seed, increment) syntax
    result = re.sub(r"IDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)", "", data_type_upper).strip()

    identity_keywords = [
        "GENERATED ALWAYS AS IDENTITY",
        "GENERATED BY DEFAULT AS IDENTITY",
        "AUTO_INCREMENT",
        "IDENTITY",
    ]

    for keyword in identity_keywords:
        result = result.replace(keyword, "").strip()

    return result if result else data_type


def normalize_identifier(identifier: Optional[str]) -> str:
    """Normalize an identifier for case-insensitive comparison.

    Args:
        identifier: Identifier to normalize

    Returns:
        Normalized identifier (lowercase)
    """
    if identifier is None:
        return ""
    # Convert to Python string to handle driver-returned objects
    return str(identifier).lower()


def strip_boolean_wrappers(expr_str: str) -> str:
    """Strip redundant parentheses around boolean sub-expressions.

    Used by normalize_expression and TableComparator for expression comparison.
    """
    tokens = [
        "=",
        "<>",
        ">=",
        "<=",
        ">",
        "<",
        " IS ",
        " AND ",
        " OR ",
        " LIKE ",
        " BETWEEN ",
    ]
    chars = list(expr_str)
    stack = []
    remove_flags = [False] * len(chars)

    for idx, ch in enumerate(chars):
        if ch == "(":
            stack.append(idx)
        elif ch == ")":
            if stack:
                start = stack.pop()
                segment = expr_str[start + 1 : idx]
                segment_upper = segment.upper()
                if any(token in segment_upper for token in tokens):
                    remove_flags[start] = True
                    remove_flags[idx] = True

    return "".join(ch for idx, ch in enumerate(chars) if not remove_flags[idx])


def strip_redundant_parens(expr_str: str) -> str:
    """Strip redundant outer parentheses from an expression."""
    while expr_str.startswith("(") and expr_str.endswith(")"):
        inner = expr_str[1:-1].strip()
        depth = 0
        balanced = True
        for ch in inner:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth < 0:
                    balanced = False
                    break
        if not balanced or depth != 0:
            break
        expr_str = inner
    return expr_str


def normalize_expression(expr: Optional[str]) -> Optional[str]:
    """Normalize an expression for comparison.

    Args:
        expr: Expression string (or other type that will be converted to string)

    Returns:
        Normalized expression

    Note:
        For Oracle, expressions may contain quoted identifiers like "PRICE"*"QUANTITY".
        We normalize by removing quotes and normalizing whitespace/case.
    """
    if expr is None:
        return None

    # Convert to string if not already (handles cases where check_expression might be an int)
    if not isinstance(expr, str):
        expr = str(expr)

    # MySQL-specific: remove character set introducers BEFORE uppercasing to preserve string literal case
    # (e.g., _utf8mb4'text' -> 'text', then we uppercase identifiers but keep string literals)
    expr = re.sub(r"_utf8mb4'([^']*)'", r"'\1'", expr, flags=re.IGNORECASE)
    expr = re.sub(r"_utf8'([^']*)'", r"'\1'", expr, flags=re.IGNORECASE)

    # Remove extra whitespace and normalize case (uppercase identifiers, but preserve string literals)
    # Strategy: Protect string literals, uppercase everything else, then restore string literals
    string_literals = []
    string_pattern = r"'([^']*)'"

    def protect_string(match: "re.Match[str]") -> str:
        string_literals.append(match.group(0))
        return f"__STRING_LITERAL_{len(string_literals)-1}__"

    # Protect string literals
    protected = re.sub(string_pattern, protect_string, expr)

    # Uppercase the protected version (identifiers and keywords)
    normalized = " ".join(protected.split()).upper()

    # Restore string literals (preserving their original case)
    for i, literal in enumerate(string_literals):
        normalized = normalized.replace(f"__STRING_LITERAL_{i}__", literal)

    # Remove "CHECK" keyword if present (case-insensitive)
    # Migration scripts may have "CHECK (expression)" while introspection returns just "expression"
    if normalized.startswith("CHECK"):
        normalized = normalized[5:].strip()
        # Remove leading/trailing whitespace after removing CHECK
        normalized = normalized.strip()

    # Remove MySQL backtick quoting before further normalization
    normalized = normalized.replace("`", "")

    # Remove outer parentheses if present (after removing CHECK keyword)
    # This handles cases like "(PRICE >= 0)" or "CHECK (PRICE >= 0)" -> "PRICE >= 0"
    if normalized.startswith("(") and normalized.endswith(")"):
        # Check if it's a balanced single set of outer parentheses
        # by counting parentheses (simple heuristic)
        paren_count = normalized.count("(")
        if paren_count == normalized.count(")") and paren_count > 0:
            # Try to determine if outer parentheses are just wrapping
            inner = normalized[1:-1].strip()
            # If inner has fewer or equal parentheses, likely just wrapping
            if inner.count("(") <= inner.count(")"):
                normalized = inner

    # Oracle-specific: Remove quotes from identifiers in expressions
    # Oracle returns: "PRICE"*"QUANTITY" but migration has: price * quantity
    # We remove quotes to normalize: PRICE*QUANTITY
    # But preserve quotes in string literals (e.g., 'text')
    # Pattern: Match quoted identifiers (double quotes) but not string literals (single quotes)
    normalized = re.sub(r'"([^"]+)"', r"\1", normalized)

    # MySQL-specific: remove backticks and character set introducers (e.g., _utf8mb4'@')
    normalized = normalized.replace("`", "")
    normalized = re.sub(r"_UTF8MB4'", "'", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"_UTF8MB4\\'([^']*)\\'", r"'\1'", normalized, flags=re.IGNORECASE)

    # Normalize whitespace around operators (*, +, -, /, =, etc.)
    # Handle compound operators first (>=, <=, <>, !=, ==) to avoid splitting them
    # Strategy: Replace compound operators with placeholders, process single operators, then restore
    compound_operators = [">=", "<=", "<>", "!=", "=="]
    compound_replacements = {}
    for i, op in enumerate(compound_operators):
        placeholder = f"__COMPOUND_OP_{i}__"
        normalized = normalized.replace(op, placeholder)
        compound_replacements[placeholder] = op

    # Now process single operators (won't match compound operators since they're replaced)
    normalized = re.sub(r"\s*([*/+\-=<>])\s*", r" \1 ", normalized)

    # Restore compound operators with proper spacing
    for placeholder, op in compound_replacements.items():
        # Replace placeholder with operator, ensuring spaces around it
        normalized = re.sub(rf"\s*{re.escape(placeholder)}\s*", f" {op} ", normalized)

    normalized = " ".join(normalized.split())  # Normalize multiple spaces

    # Remove PostgreSQL style type casts (::TEXT, ::JSONB, etc.) for comparison
    normalized = re.sub(r"::[A-Z0-9_]+", "", normalized)

    # Ensure comma spacing is normalized
    normalized = re.sub(r",\s*", ", ", normalized)

    normalized = strip_boolean_wrappers(normalized)
    normalized = strip_redundant_parens(normalized)

    return normalized


def normalize_parameters(parameters: Optional[List[Any]]) -> str:
    """Normalize procedure/function parameters for comparison.

    Args:
        parameters: List of parameter objects or strings

    Returns:
        Normalized parameter signature
    """
    if not parameters:
        return ""

    # Convert to string representation and normalize
    param_strs = []
    for param in parameters:
        if isinstance(param, str):
            param_strs.append(param.upper().strip())
        elif hasattr(param, "name") and hasattr(param, "data_type"):
            # Include direction and default_value for complete comparison
            direction = getattr(param, "direction", "IN")
            default_value = getattr(param, "default_value", None)
            param_str = f"{direction} {param.name} {param.data_type}".upper().strip()
            if default_value:
                param_str += f" = {default_value}".upper()
            param_strs.append(param_str)

    return ",".join(sorted(param_strs))


def _remove_qualifiers(node: "exp.Expression") -> "exp.Expression":
    """Remove catalog/db/table qualifiers from Column and Table nodes."""
    from sqlglot import exp

    if isinstance(node, exp.Column):
        node.set("catalog", None)
        node.set("db", None)
        node.set("table", None)
    if isinstance(node, exp.Table):
        node.set("catalog", None)
        node.set("db", None)
    return node


def _strip_wrappers(node: "exp.Expression") -> "exp.Expression":
    """Strip Cast, TryCast, and Paren wrapper nodes."""
    from sqlglot import exp

    if isinstance(node, (exp.Cast, exp.TryCast, exp.Paren)):
        inner = node.this
        if isinstance(inner, exp.Expression):
            return inner
        return node
    return node


def _sqlglot_read_dialect_for_view_normalization(dialect: str) -> Optional[str]:
    """Map dblift dialect names to sqlglot ``read`` dialect.

    Returns ``None`` when sqlglot cannot parse the dialect (skip AST normalization).

    Args:
        dialect: Dblift / caller dialect name (e.g. ``postgresql``, ``mysql``).

    Returns:
        Sqlglot dialect string for ``parse_one(..., read=...)``, or ``None``.
    """
    from db.provider_registry import ProviderRegistry

    quirks = ProviderRegistry.get_quirks(dialect.lower())
    return quirks.sqlglot_dialect


def normalize_view_definition(
    definition: Optional[str],
    dialect: str = "",
) -> str:
    """Normalize a view definition SQL string for comparison.

    Removes comments, strips qualifiers, applies sqlglot canonicalization, and
    normalizes whitespace/casing so that semantically identical view definitions
    compare as equal regardless of formatting or dialect-specific quirks.

    Args:
        definition: View definition SQL string (SELECT …).
        dialect: Database dialect for sqlglot parsing (``read``); output is still
            rendered with the ``postgres`` dialect for a stable canonical form.
            Defaults to ``""`` since PR #252 / commit ea5891f (was previously
            ``"postgresql"``). When empty,
            :func:`_sqlglot_read_dialect_for_view_normalization` returns
            ``None`` and the sqlglot canonicalisation step is **skipped**;
            only the textual normalisation (comment-stripping, whitespace,
            casing) runs. Production callers always pass an explicit dialect;
            the empty default is for dialect-agnostic test fixtures.

    Returns:
        Normalized uppercase SQL string, or ``""`` if *definition* is falsy.
    """
    if not definition:
        return ""

    # Remove single-line comments
    definition = re.sub(r"--.*$", "", definition, flags=re.MULTILINE)
    # Remove multi-line comments
    definition = re.sub(r"/\*.*?\*/", "", definition, flags=re.DOTALL)

    normalized_sql = definition.strip()

    read_dialect = _sqlglot_read_dialect_for_view_normalization(dialect)
    if read_dialect:
        try:
            import sqlglot

            # Remove materialized view storage hints (WITH [NO] DATA) before parsing
            normalized_sql = re.sub(
                r"\bWITH\s+(NO\s+)?DATA\b;?",
                "",
                normalized_sql,
                flags=re.IGNORECASE,
            ).strip()

            expression = sqlglot.parse_one(normalized_sql, read=read_dialect)

            if expression:
                expression = expression.transform(_remove_qualifiers)
                current_sql = expression.sql(
                    dialect="postgres"  # lint: allow-dialect-string: sqlglot dialect name (not framework dispatch)
                )  # lint: allow-dialect-string: sqlglot canonical form
                while True:
                    stripped = expression.transform(_strip_wrappers)
                    stripped_sql = stripped.sql(
                        dialect="postgres"  # lint: allow-dialect-string: sqlglot dialect name (not framework dispatch)
                    )  # lint: allow-dialect-string: sqlglot canonical form
                    if stripped_sql == current_sql:
                        expression = stripped
                        break
                    expression = stripped
                    current_sql = stripped_sql

                normalized_sql = expression.sql(
                    dialect="postgres"  # lint: allow-dialect-string: sqlglot dialect name (not framework dispatch)
                )  # lint: allow-dialect-string: sqlglot canonical form

        except Exception as e:
            _logger.debug(f"sqlglot parsing failed, using raw SQL: {e}")
            # Fallback to raw SQL if sqlglot parsing fails
            normalized_sql = definition

    # Remove parentheses around simple numeric literals (e.g., (0))
    normalized_sql = re.sub(r"\(\s*([0-9]+)\s*\)", r"\1", normalized_sql)

    # Remove redundant parentheses around non-subquery FROM clauses
    normalized_sql = re.sub(
        r"FROM\s+\((?!SELECT)([^()]+)\)\s+(?=(GROUP BY|WHERE|ORDER BY|HAVING|LIMIT|$))",
        lambda m: f"FROM {m.group(1)} ",
        normalized_sql,
        flags=re.IGNORECASE,
    )

    # Remove redundant quoting introduced by dialect-specific rendering
    normalized_sql = normalized_sql.replace('"', "")

    # Normalize expressions like COLUMN AS COLUMN to just COLUMN
    normalized_sql = re.sub(
        r"\b([A-Z_][A-Z0-9_]*)\s+AS\s+\1\b",
        r"\1",
        normalized_sql,
        flags=re.IGNORECASE,
    )

    # Normalize whitespace and remove spaces around dots introduced by formatting
    normalized_sql = re.sub(r"\s*\.\s*", ".", normalized_sql)
    normalized_sql = " ".join(normalized_sql.split())

    # Remove PostgreSQL style type casts (::TYPE) to avoid false positives
    normalized_sql = re.sub(r"::[A-Z0-9_\.]+", "", normalized_sql)

    # Remove schema-qualified prefixes before alias declarations (e.g., SCHEMA.TABLE AS ALIAS)
    normalized_sql = re.sub(
        r"\b([A-Z_][A-Z0-9_]*)\.([A-Z_][A-Z0-9_]*)\s+AS\s+([A-Z_][A-Z0-9_]*)",
        r"\2 AS \3",
        normalized_sql,
    )
    # Remove schema-qualified prefixes before implicit aliases (e.g., SCHEMA.TABLE ALIAS)
    normalized_sql = re.sub(
        r"\b([A-Z_][A-Z0-9_]*)\.([A-Z_][A-Z0-9_]*)\s+([A-Z_][A-Z0-9_]*)\b",
        r"\2 \3",
        normalized_sql,
    )

    # Normalize to uppercase for comparison (case-insensitive)
    return normalized_sql.upper()


def normalize_package_code(code: Optional[str]) -> str:
    """Normalize package specification or body for comparison.

    Removes extra whitespace, normalizes case of keywords, removes comments.
    Packages are typically Oracle-specific and case-insensitive for keywords.

    Args:
        code: Package specification or body code

    Returns:
        Normalized code
    """
    if not code:
        return ""

    # Remove single-line comments (-- comment)
    code = re.sub(r"--.*$", "", code, flags=re.MULTILINE)
    # Remove multi-line comments (/* comment */)
    code = re.sub(r"/\*.*?\*/", "", code, flags=re.DOTALL)

    # Normalize whitespace (collapse multiple spaces/newlines into single space)
    code = " ".join(code.split())

    # Remove spaces around parentheses and other punctuation for consistent comparison
    code = re.sub(r"\s*\(\s*", "(", code)
    code = re.sub(r"\s*\)\s*", ")", code)
    code = re.sub(r"\s*,\s*", ",", code)
    code = re.sub(r"\s*;\s*", ";", code)
    code = re.sub(r"\s*\.\s*", ".", code)  # Handle periods/dots (e.g., schema.table)

    # Normalize to uppercase for comparison (Oracle is case-insensitive for keywords)
    # but preserves case for identifiers in quotes
    return code.upper()
