"""
Oracle migration history manager.

This module handles Oracle-specific migration history table operations including
creation, recording migrations, retrieving applied migrations, and repair operations.
"""

from typing import Any, Dict, List, Optional, Union, cast

from core.logger import Log
from db.plugins.base_history_manager import (
    UNDO_HISTORY_TYPE,
    VERSIONED_HISTORY_TYPES,
    BaseHistoryManager,
)


class OracleHistoryManager(BaseHistoryManager):
    """Manages Oracle migration history operations."""

    # Oracle stores unquoted identifiers as UPPERCASE
    DEFAULT_HISTORY_TABLE = "DBLIFT_SCHEMA_HISTORY"

    def _get_default_table_name(self) -> str:
        """Return the default history table name in Oracle's native UPPERCASE."""
        return self.DEFAULT_HISTORY_TABLE

    def __init__(
        self,
        query_executor: Any,
        schema_operations: Any,
        config: Any,
        log: Optional[Log] = None,
    ) -> None:
        """Initialize the history manager.

        Args:
            query_executor: Query executor instance
            schema_operations: Schema operations instance
            config: Configuration object
            log: Optional logger
        """
        super().__init__(query_executor, schema_operations, config, log)
        # config reserved; not used by this implementation

    def create_migration_history_table_if_not_exists(
        self,
        connection: Any,
        schema: str,
        create_schema: bool = False,
        table_name: str = "dblift_schema_history",
    ) -> None:
        """Create the migration history table if it doesn't exist."""
        from db.object_naming import get_normalized_object_name

        dblift_table_name = get_normalized_object_name(table_name, "oracle")

        self.log.debug(
            f"Creating migration history table if not exists: {schema}.{dblift_table_name}"
        )

        try:
            if create_schema:
                self.schema_operations.create_schema_if_not_exists(connection, schema)

            # Check if table exists
            table_exists = self.query_executor.table_exists(connection, schema, dblift_table_name)
            if table_exists:
                if create_schema:
                    self._check_baseline_safety(connection, schema, dblift_table_name)
                self.log.debug(
                    f"Migration history table {schema}.{dblift_table_name} already exists"
                )
                return

            # Ensure schema exists before creating table
            self.schema_operations.create_schema_if_not_exists(connection, schema)

            # Use uppercase table name for Oracle (native case)
            qualified_table = self.query_executor.get_schema_qualified_name(
                schema, dblift_table_name
            )
            sql = f"""
            CREATE TABLE {qualified_table} (
                INSTALLED_RANK NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                VERSION VARCHAR2(50),
                DESCRIPTION VARCHAR2(200) NOT NULL,
                TYPE VARCHAR2(20) NOT NULL,
                SCRIPT VARCHAR2(1000) NOT NULL,
                CHECKSUM NUMBER,
                INSTALLED_BY VARCHAR2(100) NOT NULL,
                INSTALLED_ON TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                EXECUTION_TIME NUMBER NOT NULL,
                SUCCESS NUMBER(1) NOT NULL
            )
            """
            self.query_executor.execute_statement(connection, sql)
            self.log.info(
                f"Created migration history table in schema {schema} as {dblift_table_name}"
            )

        except Exception as e:
            # If table already exists, that's fine
            # Check for Oracle error code ORA-00955 (name is already used by an existing object)
            # which is locale-independent
            error_str = str(e).lower()
            if (
                "already exists" in error_str
                or "name is already used" in error_str
                or "ora-00955" in error_str
                or "existe déjà" in error_str  # French: already exists
                or "existe já" in error_str  # Portuguese: already exists
            ):
                self.log.debug(
                    f"Migration history table {schema}.{dblift_table_name} already exists"
                )
                return
            self.log.error(f"Error creating migration history table: {str(e)}")
            raise

    def create_history_table(self, schema: str, table_name: str = "dblift_schema_history") -> str:
        """Generate the SQL to create a migration history table in the given schema with the given table name."""
        from db.object_naming import get_normalized_object_name

        dblift_table_name = get_normalized_object_name(table_name, "oracle")
        qualified_table = self.query_executor.get_schema_qualified_name(schema, dblift_table_name)

        return f"""
            CREATE TABLE {qualified_table} (
                INSTALLED_RANK NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                VERSION VARCHAR2(50),
                DESCRIPTION VARCHAR2(200) NOT NULL,
                TYPE VARCHAR2(20) NOT NULL,
                SCRIPT VARCHAR2(1000) NOT NULL,
                CHECKSUM NUMBER,
                INSTALLED_BY VARCHAR2(100) NOT NULL,
                INSTALLED_ON TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                EXECUTION_TIME NUMBER NOT NULL,
                SUCCESS NUMBER(1) NOT NULL
            )
        """

    def record_migration(
        self,
        connection: Any,
        schema: str,
        migration_info: Dict[str, Any],
        table_name: Optional[str] = None,
    ) -> None:
        """Record a migration in the history table.

        Args:
            schema: Schema name
            migration_info: Dictionary containing migration information
            table_name: Custom history table name (default: dblift_schema_history)
        """
        from db.object_naming import get_normalized_object_name

        raw_table = table_name or "dblift_schema_history"
        dblift_table_name = get_normalized_object_name(raw_table, "oracle")

        # Check if table exists
        if not self.query_executor.table_exists(connection, schema, dblift_table_name):
            self.create_migration_history_table_if_not_exists(connection, schema, True, raw_table)

        try:
            # Insert migration record - do NOT include INSTALLED_RANK, let Oracle assign it
            # Use SYSDATE directly to avoid timestamp conversion issues
            qualified_table = self.query_executor.get_schema_qualified_name(
                schema, dblift_table_name
            )
            # Column names are uppercase (unquoted) as per Oracle standards for our objects
            insert_sql = f"""
            INSERT INTO {qualified_table} (
                VERSION, DESCRIPTION, TYPE, SCRIPT,
                CHECKSUM, INSTALLED_BY, INSTALLED_ON, EXECUTION_TIME, SUCCESS
            ) VALUES (?, ?, ?, ?, ?, ?, SYSDATE, ?, ?)
            """

            # Convert boolean to number (0/1) for Oracle
            success_value = 1 if migration_info.get("success", True) else 0

            params = self._build_migration_params(migration_info, success_value)

            self.query_executor.execute_statement(connection, insert_sql, params=params)

            self.log.debug(f"Migration recorded in schema {schema}: {migration_info.get('script')}")
        except Exception as e:
            error_msg = f"Error recording migration in schema {schema}: {str(e)}"
            self.log.error(error_msg)
            raise

    def record_undo(
        self,
        connection: Any,
        schema: str,
        version: str,
        table_name: Optional[str] = None,
        script_name: Optional[str] = None,
    ) -> bool:
        """Record an undo operation in the migration history.

        Args:
            schema: Schema name
            version: Version being undone
            table_name: Custom history table name
            script_name: Original migration script name, if available

        Returns:
            bool: True if undo was recorded successfully
        """
        try:
            undo_info = {
                "version": version,
                "description": f"Undo migration {version}",
                "type": UNDO_HISTORY_TYPE,
                "script": self._undo_script_name(version, script_name),
                # Batch-6 BUG-02: typed NULL on an INT column fails on strict
                # drivers; ``0`` is the existing sentinel for "no checksum".
                "checksum": 0,
                "installed_by": "dblift",
                "execution_time": 0,
                "success": True,
            }

            self.record_migration(connection, schema, undo_info, table_name)
            return True

        except Exception as e:
            self.log.error(f"Error recording undo for version {version}: {str(e)}")
            return False

    def get_applied_migrations(
        self, connection: Any, schema: str, table_name: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Get list of applied migrations from history table.

        Args:
            schema: Schema name
            table_name: Custom history table name (default: DBLIFT_SCHEMA_HISTORY)

        Returns:
            List of dictionaries containing migration information
        """
        from db.object_naming import get_normalized_object_name

        raw_table = table_name or "dblift_schema_history"
        table_name_to_use = get_normalized_object_name(raw_table, "oracle")

        qualified_table = self.query_executor.get_schema_qualified_name(schema, table_name_to_use)

        if not self.query_executor.table_exists(connection, schema, table_name_to_use):
            return []
        # Use uppercase column names to match our table definition
        # Oracle will return results with column names in uppercase
        query = f"""
        SELECT SCRIPT, INSTALLED_RANK, VERSION, DESCRIPTION,
               TYPE, CHECKSUM, INSTALLED_BY, INSTALLED_ON,
               EXECUTION_TIME, SUCCESS
        FROM {qualified_table}
        ORDER BY INSTALLED_RANK
        """

        try:
            results = self.query_executor.execute_query(connection, query)

            # Normalize the results to Python format
            normalized_results = self._normalize_migration_results(results)

            return normalized_results

        except Exception as e:
            error_msg = f"Error getting applied migrations from schema {schema}: {str(e)}"
            self.log.error(error_msg)
            raise

    def repair_migration_history(
        self,
        connection: Any,
        schema: str,
        script_name: str,
        checksum: Union[int, str],
        success_value: Optional[bool] = None,
        table_name: Optional[str] = None,
    ) -> bool:
        """Repair a migration record in the history table.

        Args:
            schema: Schema name
            script_name: Script name to repair
            checksum: New checksum value
            success_value: Success status (None to set to NULL/failed, True/False for explicit status)
            table_name: Custom history table name
        Returns:
            bool: True if a history row was updated, False otherwise.
        """
        from db.object_naming import get_normalized_object_name

        raw_table = table_name or "dblift_schema_history"
        table_name_to_use = get_normalized_object_name(raw_table, "oracle")

        qualified_table = self.query_executor.get_schema_qualified_name(schema, table_name_to_use)

        # Build update SQL with Oracle uppercase column names
        if success_value is None:
            # Mark as failed (0) — SUCCESS is NOT NULL since story 17-3; NULL is no longer valid
            update_sql = f"""
            UPDATE {qualified_table}
            SET CHECKSUM = ?, SUCCESS = 0
            WHERE SCRIPT = ?
            """
            params: List[Any] = [checksum, script_name]
        else:
            # Repair with explicit success value (useful for marking migrations as applied)
            success_num = 1 if success_value else 0
            update_sql = f"""
            UPDATE {qualified_table}
            SET CHECKSUM = ?, SUCCESS = ?
            WHERE SCRIPT = ?
            """
            params = [checksum, success_num, script_name]

        try:
            affected_rows = cast(
                int, self.query_executor.execute_statement(connection, update_sql, params=params)
            )
            if affected_rows > 0:
                success_str = "NULL" if success_value is None else str(success_value)
                self.log.debug(
                    f"Migration record repaired in schema {schema}: {script_name} (success={success_str})"
                )
            else:
                self.log.warning(
                    f"No migration record found to repair in schema {schema}: {script_name}"
                )
            return affected_rows > 0
        except Exception as e:
            error_msg = f"Error repairing migration record in schema {schema}: {str(e)}"
            self.log.error(error_msg)
            raise

    def _normalize_migration_results(self, results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Normalize migration results from Oracle format to standard format.

        Args:
            results: Raw results from Oracle query

        Returns:
            Normalized results with proper key mapping and status calculation
        """
        # Convert keys to lowercase (Oracle returns uppercase column names)
        lowercase_results = []
        for row in results:
            lowercase_row = {}
            for key, value in row.items():
                lowercase_key = key.lower() if isinstance(key, str) else key
                lowercase_row[lowercase_key] = value
            lowercase_results.append(lowercase_row)

        # Handle special case for success field which should be a boolean
        for row in lowercase_results:
            if row.get("success") is not None:
                row["success"] = bool(int(row["success"]))

        # Add status field based on success value, handling re-applied migrations correctly
        # (This logic mirrors the base history-manager implementation)
        undone_versions = {
            row["version"]
            for row in lowercase_results
            if row.get("type") == "UNDO_SQL" and row.get("success")
        }

        # Find the latest installed_rank for each versioned migration
        version_highest_rank: Dict[str, int] = {}
        version_latest_success: Dict[str, bool] = {}
        for row in lowercase_results:
            version_val = row.get("version")
            if version_val is None:
                continue
            version = str(version_val)
            # Track highest installed_rank for each version
            if row.get("installed_rank", 0) > version_highest_rank.get(version, 0):
                version_highest_rank[version] = row.get("installed_rank", 0)

            # Track latest success status for each version (versioned rows only).
            # ``SQL`` is the versioned type for .sql scripts and ``PYTHON`` for
            # scripted formats; both must be tracked, or a Python migration's
            # attempts are invisible here and it can never be reported UNDONE.
            if row.get("type") in VERSIONED_HISTORY_TYPES:
                # Initialize if not already present
                if version not in version_latest_success:
                    version_latest_success[version] = False

                # Update if this row has a higher installed_rank
                if row.get("installed_rank", 0) > version_highest_rank.get(version, 0) - 1:
                    version_highest_rank[version] = row.get("installed_rank", 0)
                    version_latest_success[version] = bool(row.get("success"))

        # Add a 'status' field based on the success value
        for row in lowercase_results:
            version_val = row.get("version")
            if version_val is None:
                continue
            version = str(version_val)
            # Check if this is a DELETE type entry to set status
            if row.get("type") == "DELETE":
                row["status"] = "DELETED"
            elif row["success"] is True or row["success"] == 1:
                if row.get("type") == "UNDO_SQL":
                    row["status"] = "SUCCESS"
                elif row.get("type") in VERSIONED_HISTORY_TYPES:
                    if version in undone_versions and not version_latest_success.get(version):
                        if row.get("installed_rank") == version_highest_rank.get(version, 0):
                            row["status"] = "UNDONE"
                        else:
                            row["status"] = "UNDONE"
                    else:
                        row["status"] = "SUCCESS"
                else:
                    row["status"] = "SUCCESS"
            elif row["success"] is False or row["success"] == 0:
                row["status"] = "FAILED"
            else:
                row["status"] = "NEEDS_REPAIR"

        return lowercase_results

    def get_row_limit_clause(self, n: int = 1) -> str:
        """Oracle-specific row limit clause."""
        return f"FETCH FIRST {n} ROWS ONLY"

    def _get_first_value(self, result: Any) -> Any:
        """Get the first value from the first row of a query result.

        This safely handles the case where the result is a list of dictionaries
        (which is the format returned by execute_query).

        Args:
            result: The result from execute_query

        Returns:
            The first value in the first row, or None if result is empty
        """
        if not result or len(result) == 0:
            return None

        # Get the first row
        first_row = result[0]

        # Extract the first value from the dictionary
        return list(first_row.values())[0] if first_row else None
