"""Stable schema-model imports for extensions."""

from dblift.core.sql_model import (
    DatabaseLink,
    Event,
    Extension,
    ForeignDataWrapper,
    ForeignServer,
    Index,
    LinkedServer,
    Module,
    Package,
    Parameter,
    ParseResult,
    Partition,
    Procedure,
    Sequence,
    SqlColumn,
    SqlConstraint,
    SqlObject,
    SqlObjectType,
    SqlStatementType,
    Synonym,
    Table,
    Trigger,
    UserDefinedType,
    View,
    get_constraint_type_name,
    get_object_type_name,
    quote_identifier,
    quote_qualified,
)
from dblift.core.sql_model.base import ConstraintType
from dblift.core.sql_model.dialect import dialect_requires_schema, get_sqlglot_dialect
from dblift.core.sql_model.feature_gates import supports_feature
from dblift.core.sql_model.server_info import ServerInfo
from dblift.core.sql_model.table_canonicalizer import TableCanonicalizer
from dblift.core.sql_model.table_options import TableOptions

__all__ = [
    "ConstraintType",
    "DatabaseLink",
    "Event",
    "Extension",
    "ForeignDataWrapper",
    "ForeignServer",
    "Index",
    "LinkedServer",
    "Module",
    "Package",
    "Parameter",
    "ParseResult",
    "Partition",
    "Procedure",
    "Sequence",
    "ServerInfo",
    "SqlColumn",
    "SqlConstraint",
    "SqlObject",
    "SqlObjectType",
    "SqlStatementType",
    "Synonym",
    "Table",
    "TableCanonicalizer",
    "TableOptions",
    "Trigger",
    "UserDefinedType",
    "View",
    "dialect_requires_schema",
    "get_constraint_type_name",
    "get_object_type_name",
    "get_sqlglot_dialect",
    "quote_identifier",
    "quote_qualified",
    "supports_feature",
]
