"""Column converter for converting column diffs to SQL.

Dialect-specific ALTER TABLE SQL for column changes is generated by
``BaseQuirks`` hook methods (``render_column_nullable_change``,
``render_column_default_change``, ``render_column_type_change``,
``render_column_collation_change``).  Each dialect plugin overrides the
hooks it supports; the default returns ``None`` so the converter emits a
warning instead of incorrect SQL.
"""

import logging
from typing import List, Optional, Tuple

from core.comparison.diff_models import ColumnDiff
from core.sql_generator.diff_converters.base_converter import BaseConverter
from core.sql_generator.sql_statement import GenerationOptions, SqlStatement

logger = logging.getLogger(__name__)


class ColumnConverter(BaseConverter):
    """Convert ColumnDiff to SQL statements via dialect quirks hooks."""

    def convert(  # type: ignore[override]
        self,
        column_diff: ColumnDiff,
        table_name: str,
        options: GenerationOptions,
    ) -> List[SqlStatement]:
        """Convert column diff to SQL statements.

        Args:
            column_diff: Column diff to convert
            table_name: Name of the table
            options: Generation options

        Returns:
            List of SQL statements
        """
        statements: List[SqlStatement] = []

        schema, name = self._parse_table_name(table_name)
        formatted_table = self._format_table_name(schema, name)
        formatted_column = self._quote_identifier(column_diff.column_name)

        from db.provider_registry import ProviderRegistry

        quirks = ProviderRegistry.get_quirks((self.dialect or "").lower())

        if column_diff.nullable_diff:
            stmt = quirks.render_column_nullable_change(
                column_diff, formatted_table, formatted_column, self.dialect
            )
            if stmt is None:
                logger.warning(f"Unsupported dialect for nullable change: {self.dialect}")
            elif stmt:
                statements.append(stmt)  # type: ignore[arg-type]

        if column_diff.default_diff:
            stmt = quirks.render_column_default_change(
                column_diff, formatted_table, formatted_column, self.dialect
            )
            if stmt is None:
                logger.warning(f"Unsupported dialect for default change: {self.dialect}")
            elif stmt:
                statements.append(stmt)  # type: ignore[arg-type]

        if column_diff.data_type_diff:
            stmt = quirks.render_column_type_change(
                column_diff, formatted_table, formatted_column, self.dialect
            )
            if stmt is None:
                logger.warning(f"Unsupported dialect for type change: {self.dialect}")
            elif stmt:
                statements.append(stmt)  # type: ignore[arg-type]

        if column_diff.collation_diff:
            stmt = quirks.render_column_collation_change(
                column_diff, formatted_table, formatted_column, self.dialect
            )
            if stmt is None:
                logger.warning(f"Unsupported dialect for collation change: {self.dialect}")
            elif stmt:
                statements.append(stmt)  # type: ignore[arg-type]

        return statements

    def _parse_table_name(self, table_name: str) -> Tuple[Optional[str], str]:
        """Parse table name into schema and name."""
        if "." in table_name:
            parts = table_name.split(".", 1)
            return parts[0], parts[1]
        return None, table_name

    def _format_table_name(self, schema: Optional[str], name: str) -> str:
        """Format table name with optional schema prefix."""
        if schema:
            return f"{self._quote_identifier(schema)}.{self._quote_identifier(name)}"
        return self._quote_identifier(name)
