"""Upgrade guard for an Oracle schema 4.8.0 stored with its exact case.

4.8.0 used ``schema:`` verbatim, so an unquoted lowercase value created a
lowercase user and wrote history there. An unquoted name is now uppercased.
If ``ALL_USERS`` still contains that exact spelling, the run must stop
before any object or history row is created, and the message must tell the
operator to quote the schema. A config value that includes the double quotes
keeps that lowercase user.

Prerequisites: Oracle at localhost:1521, service FREEPDB1, ``system`` /
``oracle``.
"""

import uuid

import pytest

from dblift.api import DBLiftClient
from dblift.config.dblift_config import DbliftConfig
from dblift.core.migration.migration import calculate_migration_script_checksum
from dblift.db.plugins.oracle.config import OracleConfig
from dblift.db.provider_registry import ProviderRegistry
from tests.integration.helpers.migration_helper import create_versioned_migration

pytestmark = [pytest.mark.integration, pytest.mark.oracle]

HOST = "localhost"
PORT = 1521
SERVICE = "FREEPDB1"
ADMIN_USER = "system"
ADMIN_PASSWORD = "oracle"

_HISTORY_DDL = """
    CREATE TABLE {qualified} (
        INSTALLED_RANK NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        VERSION VARCHAR2(50),
        DESCRIPTION VARCHAR2(200) NOT NULL,
        TYPE VARCHAR2(20) NOT NULL,
        SCRIPT VARCHAR2(1000) NOT NULL,
        CHECKSUM NUMBER,
        INSTALLED_BY VARCHAR2(100) NOT NULL,
        INSTALLED_ON TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        EXECUTION_TIME NUMBER NOT NULL,
        SUCCESS NUMBER(1) NOT NULL
    )
"""


def _admin_config() -> DbliftConfig:
    return DbliftConfig(
        database=OracleConfig(
            type="oracle",
            host=HOST,
            port=PORT,
            service_name=SERVICE,
            username=ADMIN_USER,
            password=ADMIN_PASSWORD,
        )
    )


def _scalar(rows):
    row = rows[0]
    return next(iter(row.values())) if isinstance(row, dict) else row[0]


def _user_count(provider, username: str) -> int:
    rows = provider.execute_query(
        "SELECT COUNT(*) AS c FROM ALL_USERS WHERE username = ?", [username]
    )
    return int(_scalar(rows))


def _table_count(provider, owner: str, table_name: str) -> int:
    rows = provider.execute_query(
        "SELECT COUNT(*) AS c FROM ALL_TABLES WHERE OWNER = ? AND TABLE_NAME = ?",
        [owner, table_name],
    )
    return int(_scalar(rows))


def _history_count(provider, schema: str) -> int:
    rows = provider.execute_query(f'SELECT COUNT(*) AS c FROM "{schema}"."DBLIFT_SCHEMA_HISTORY"')
    return int(_scalar(rows))


def _migrate(schema: str, migrations_dir):
    config = DbliftConfig(
        database=OracleConfig(
            type="oracle",
            host=HOST,
            port=PORT,
            service_name=SERVICE,
            username=ADMIN_USER,
            password=ADMIN_PASSWORD,
            schema=schema,
        )
    )
    config.migrations.directory = str(migrations_dir)
    provider = ProviderRegistry.create_provider(config)
    provider.create_connection()
    try:
        client = DBLiftClient(provider=provider, migrations_dir=migrations_dir, config=config)
        return client.migrate()
    finally:
        provider.close()


def test_unquoted_lowercase_schema_stops_and_quoted_keeps_it(tmp_path):
    """A 4.8.0 lowercase user with history is not replayed onto an uppercase user."""
    schema = f"u{uuid.uuid4().hex[:8]}"
    schema_upper = schema.upper()
    quoted = f'"{schema}"'
    v1_sql = "CREATE TABLE marker (id NUMBER);\n"
    v2_sql = "CREATE TABLE widget (id NUMBER);\n"

    migrations_dir = tmp_path / "migrations"
    v1_path = create_versioned_migration(migrations_dir, "1.0.0", "create_marker", v1_sql)
    create_versioned_migration(migrations_dir, "1.1.0", "create_widget", v2_sql)
    checksum = calculate_migration_script_checksum(v1_path.read_text())

    admin = ProviderRegistry.create_provider(_admin_config())
    admin.create_connection()
    try:
        admin.execute_statement(
            f'CREATE USER "{schema}" IDENTIFIED BY "Dblift_ora_1" '
            "DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS"
        )
        admin.execute_statement(f'GRANT CONNECT, RESOURCE, CREATE TABLE TO "{schema}"')
        admin.execute_statement(
            _HISTORY_DDL.format(qualified=f'"{schema}"."DBLIFT_SCHEMA_HISTORY"')
        )
        admin.execute_statement(
            f'INSERT INTO "{schema}"."DBLIFT_SCHEMA_HISTORY" '
            "(VERSION, DESCRIPTION, TYPE, SCRIPT, CHECKSUM, INSTALLED_BY, "
            "EXECUTION_TIME, SUCCESS) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            params=[
                "1.0.0",
                "create marker",
                "SQL",
                v1_path.name,
                checksum,
                "dblift",
                0,
                1,
            ],
        )
        assert _user_count(admin, schema) == 1
        assert _user_count(admin, schema_upper) == 0
        assert _history_count(admin, schema) == 1

        blocked = _migrate(schema, migrations_dir)

        assert not blocked.success
        assert blocked.error_message
        assert "Quote the schema name in config" in blocked.error_message
        assert "keep the existing lowercase schema" in blocked.error_message
        assert f"schema: '\"{schema}\"'" in blocked.error_message
        assert _user_count(admin, schema_upper) == 0, "uppercase user was created before the stop"
        assert _history_count(admin, schema) == 1
        assert _table_count(admin, schema, "WIDGET") == 0
        assert _table_count(admin, schema, "MARKER") == 0
        assert _table_count(admin, schema_upper, "WIDGET") == 0
        assert _table_count(admin, schema_upper, "DBLIFT_SCHEMA_HISTORY") == 0

        kept = _migrate(quoted, migrations_dir)

        assert kept.success, kept.error_message
        assert _user_count(admin, schema_upper) == 0
        assert _user_count(admin, schema) == 1
        assert _table_count(admin, schema, "WIDGET") == 1
        assert _table_count(admin, schema_upper, "WIDGET") == 0
        assert _history_count(admin, schema) == 2
        assert _table_count(admin, schema_upper, "DBLIFT_SCHEMA_HISTORY") == 0
    finally:
        for name in (schema, schema_upper):
            try:
                if _user_count(admin, name):
                    admin.execute_statement(f'DROP USER "{name}" CASCADE')
            except Exception:
                pass
        close = getattr(admin, "close", None)
        if callable(close):
            close()
