"""Tests for core.sql_generator.table_ddl_render."""

import pytest

from core.sql_generator.table_ddl_render import render_table_ddl
from core.sql_model.base import ConstraintType, SqlColumn, SqlConstraint
from core.sql_model.table import Table


def _orders_table(dialect: str = "postgresql") -> Table:
    cols = [
        SqlColumn(name="id", data_type="serial", is_nullable=False, is_identity=True),
        SqlColumn(name="user_id", data_type="int4", is_nullable=False),
        SqlColumn(name="total_amount", data_type="numeric(10, 2)", is_nullable=False),
        SqlColumn(
            name="status",
            data_type="varchar(20)",
            is_nullable=True,
            default_value="'pending'::character varying",
        ),
        SqlColumn(
            name="placed_at",
            data_type="timestamptz(6)",
            is_nullable=True,
            default_value="now()",
        ),
    ]
    constraints = [
        SqlConstraint(
            constraint_type=ConstraintType.PRIMARY_KEY,
            name="orders_pkey",
            column_names=["id"],
        ),
        SqlConstraint(
            constraint_type=ConstraintType.FOREIGN_KEY,
            name="orders_user_id_fkey",
            column_names=["user_id"],
            reference_table="users",
            reference_columns=["id"],
        ),
    ]
    return Table(
        name="orders",
        schema="dblift_demo",
        columns=cols,
        constraints=constraints,
        dialect=dialect,
    )


@pytest.mark.unit
class TestRenderTableDdl:
    def test_postgresql_native_types_preserved(self):
        sql = render_table_ddl(_orders_table(), dialect="postgresql")
        assert "serial" in sql.lower()
        assert "int4" in sql.lower()
        assert "numeric(10, 2)" in sql.lower()
        assert "timestamptz(6)" in sql.lower()
        # ANSI-ified forms must NOT appear (sqlglot-style rewrites)
        assert "GENERATED BY DEFAULT AS IDENTITY" not in sql.upper()
        assert "DECIMAL(10, 2)" not in sql.upper()
        assert "CAST(" not in sql.upper()

    def test_format_for_compare_trims_trailing_whitespace(self):
        # Build with trailing spaces in default to trigger rstrip path
        col = SqlColumn(name="x", data_type="int4", is_nullable=False)
        table = Table(name="t", schema="s", columns=[col], constraints=[], dialect="postgresql")
        sql = render_table_ddl(table, dialect="postgresql", format_for_compare=True)
        for line in sql.splitlines():
            assert line == line.rstrip()

    def test_format_for_compare_ensures_semicolon(self):
        col = SqlColumn(name="x", data_type="int4", is_nullable=False)
        table = Table(name="t", schema="s", columns=[col], constraints=[], dialect="postgresql")
        sql = render_table_ddl(table, dialect="postgresql", format_for_compare=True)
        assert sql.endswith(";")

    def test_format_for_compare_collapses_blank_runs(self):
        col = SqlColumn(name="x", data_type="int4", is_nullable=False)
        table = Table(name="t", schema="s", columns=[col], constraints=[], dialect="postgresql")
        # Inject artificial blank-line run via post-render manipulation
        from core.sql_generator.table_ddl_render import _format_for_compare

        polluted = "CREATE TABLE t (\n\n\n\n  x int4 NOT NULL\n);"
        out = _format_for_compare(polluted)
        assert "\n\n\n" not in out

    def test_format_for_compare_no_change_when_off(self):
        col = SqlColumn(name="x", data_type="int4", is_nullable=False)
        table = Table(name="t", schema="s", columns=[col], constraints=[], dialect="postgresql")
        raw = render_table_ddl(table, dialect="postgresql", format_for_compare=False)
        compared = render_table_ddl(table, dialect="postgresql", format_for_compare=True)
        # Compared has trailing semicolon; raw may not
        assert compared.endswith(";")
        # Compared rstrips lines; raw may have trailing spaces — but content equivalent
        normalized_raw = "\n".join(line.rstrip() for line in raw.splitlines()).strip()
        if not normalized_raw.endswith(";"):
            normalized_raw += ";"
        assert compared == normalized_raw


@pytest.mark.unit
class TestSnapshotLiveParity:
    """Acceptance: snapshot-loaded Table and live-introspected Table produce identical
    DDL when canonicalized. Simulates the bug fix end-to-end.
    """

    def test_orders_byte_equal_post_canonicalization(self):
        """Same logical schema, different default-flag presence → identical render after canonicalization."""
        from core.sql_model.table_canonicalizer import TableCanonicalizer

        snapshot_table = _orders_table()  # All flags None (snapshot JSON shape)

        live_table = _orders_table()  # Same shape, but live introspection adds defaults
        for c in live_table.constraints:
            c.is_deferrable = False
            c.initially_deferred = False
            c.is_enabled = True
            c.is_validated = True

        canonicalizer = TableCanonicalizer()
        canonicalizer.canonicalize(snapshot_table)
        canonicalizer.canonicalize(live_table)

        snap_sql = render_table_ddl(snapshot_table, dialect="postgresql", format_for_compare=True)
        live_sql = render_table_ddl(live_table, dialect="postgresql", format_for_compare=True)

        assert snap_sql == live_sql
