"""Demo script: showcase all Rich console output features added in PR #229.

Run with:  python scripts/demo_rich_output.py
"""

import time

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn
from rich.syntax import Syntax
from rich.table import Table
from rich.text import Text
from rich.theme import Theme
from rich.traceback import install as install_rich_traceback
from rich.tree import Tree

DBLIFT_THEME = Theme(
    {
        "log.debug": "dim",
        "log.info": "default",
        "log.warn": "yellow",
        "log.error": "bold red",
        "log.notice": "bold green",
    }
)

console = Console(theme=DBLIFT_THEME, highlight=False, soft_wrap=True, emoji=False, markup=True)

SECTION = "[bold cyan]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[/bold cyan]"


def section(title: str) -> None:
    console.print()
    console.print(SECTION)
    console.print(f"[bold white]  {title}[/bold white]")
    console.print(SECTION)
    console.print()


# ── 1. Severity-themed log output ────────────────────────────────────────────
section("1 / SEVERITY-THEMED LOG OUTPUT  (ConsoleLog)")

console.print("[log.debug]DEBUG   Loading config from /etc/dblift/dblift.conf[/log.debug]")
console.print("[log.info]INFO    Connected to database 'myapp_prod' (PostgreSQL 16.2)[/log.info]")
console.print(
    "[log.warn]WARN    Baseline migration V1 checksum mismatch — skipping integrity check[/log.warn]"
)
console.print(
    "[log.error]ERROR   Cannot connect to host db.example.com:5432 — Connection refused[/log.error]"
)
console.print("[log.notice]NOTICE  Migration V3.2.1 applied successfully (342 ms)[/log.notice]")

# ── 2. Diff: header panel ────────────────────────────────────────────────────
section("2 / DIFF COMMAND — header panel  (border_style colored)")

panel_found = Panel(
    "Differences detected — see sections below",
    title="SCHEMA DIFFERENCES FOUND",
    box=box.HEAVY,
    border_style="bold red",
    expand=True,
)
console.print(panel_found)

# ── 3. Diff: hierarchical Tree ───────────────────────────────────────────────
section("3 / DIFF COMMAND — hierarchical Tree output")

missing = Tree("Missing Tables (2)")
missing.add("audit_log")
missing.add("user_sessions")
console.print(missing)
console.print()

extra = Tree("Extra Tables (1)")
extra.add("tmp_import_staging")
console.print(extra)
console.print()

root = Tree("Modified Tables (3)")

t1 = root.add("Table 'orders' [ERROR]")
cols1 = t1.add("Missing columns (2)")
cols1.add("payment_method")
cols1.add("fulfilled_at")
mod1 = t1.add("Modified columns (1)")
c1 = mod1.add("Column 'total_amount' [WARNING]")
c1.add("data_type: numeric(10,2) → numeric(14,4)")
c1.add("nullable: True → False")

t2 = root.add("Table 'products' [WARNING]")
idx2 = t2.add("Missing indexes (1)")
idx2.add("idx_products_sku")
extra2 = t2.add("Extra columns (1)")
extra2.add("legacy_barcode")

t3 = root.add("Table 'users' [INFO]")
cons3 = t3.add("Modified constraints (1)")
cons3.add("chk_email: check (email LIKE '%@%') → check (email ~* '^[^@]+@[^@]+$')")

console.print(root)
console.print()

views_root = Tree("Modified Views (1)")
v1 = views_root.add("View 'v_active_orders'")
v1.add("Definition changed")
console.print(views_root)

# ── 4. Diff: SQL syntax preview ──────────────────────────────────────────────
section("4 / DIFF COMMAND — SQL syntax-highlighted preview  (rich.syntax)")

sql = """\
-- Generated by dblift diff
ALTER TABLE orders
    ADD COLUMN payment_method VARCHAR(50),
    ADD COLUMN fulfilled_at   TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN total_amount TYPE NUMERIC(14, 4),
    ALTER COLUMN total_amount SET NOT NULL;

CREATE INDEX idx_products_sku ON products (sku);

ALTER VIEW v_active_orders AS
    SELECT o.id, o.total_amount, o.payment_method
    FROM   orders o
    WHERE  o.fulfilled_at IS NOT NULL;
"""

syntax = Syntax(sql, "sql", theme="monokai", line_numbers=True)
console.print(syntax)

# ── 5. Diff: summary footer panel (FAILED) ──────────────────────────────────
section("5a / DIFF COMMAND — summary footer FAILED  (bold red border + colored status)")

footer_body = Text()
footer_body.append("Total differences: 7\n")
footer_body.append("  Errors: 2\n")
footer_body.append("  Warnings: 3\n")
footer_body.append("  Info: 2\n")
footer_body.append("Status: ")
footer_body.append("FAILED", style="bold red")

footer_panel = Panel(
    footer_body, title="SUMMARY", box=box.HEAVY, border_style="bold red", expand=True
)
console.print(footer_panel)

section("5b / DIFF COMMAND — summary footer WARNING")

warn_body = Text()
warn_body.append("Total differences: 3\n")
warn_body.append("  Warnings: 3\n")
warn_body.append("Status: ")
warn_body.append("WARNING", style="yellow")

console.print(Panel(warn_body, title="SUMMARY", box=box.HEAVY, border_style="yellow", expand=True))

section("5c / DIFF COMMAND — summary footer SUCCESS")

ok_body = Text()
ok_body.append("Total differences: 0\n")
ok_body.append("Status: ")
ok_body.append("SUCCESS", style="bold green")

console.print(
    Panel(ok_body, title="SUMMARY", box=box.HEAVY, border_style="bold green", expand=True)
)

# ── 6. Migration status table ────────────────────────────────────────────────
section("6 / INFO / MIGRATE — migration status table  (colored State column)")

_STATE_STYLE = {
    "success": "bold green",
    "failed": "bold red",
    "pending": "yellow",
    "baseline": "dim",
    "ignored": "dim",
    "missing": "bold red",
}


def state_cell(label: str) -> Text:
    t = Text(label)
    style = _STATE_STYLE.get(label.lower(), "")
    if style:
        t.stylize(style)
    return t


table = Table(box=box.ROUNDED, show_header=True, header_style="bold")
for col, justify in [
    ("Version", "left"),
    ("Description", "left"),
    ("Type", "left"),
    ("Installed On", "left"),
    ("State", "left"),
    ("Exec Time", "right"),
]:
    table.add_column(col, justify=justify)

rows_data = [
    ("1", "baseline", "SQL", "2025-01-10 09:00", "Baseline", "12 ms"),
    ("2.1", "add users table", "SQL", "2025-03-04 14:22", "Success", "87 ms"),
    ("2.2", "add orders table", "SQL", "2025-03-04 14:23", "Success", "134 ms"),
    ("3.1", "seed reference data", "SQL", "2025-04-01 11:05", "Success", "3,201 ms"),
    ("3.1.1", "backport hotfix", "SQL", "2025-04-02 08:00", "Failed", "522 ms"),
    ("3.2.1", "add payment method", "SQL", "", "Pending", ""),
    ("3.2.2", "add fulfilled at", "SQL", "", "Pending", ""),
]
for ver, desc, typ, installed, state, exec_time in rows_data:
    table.add_row(ver, desc, typ, installed, state_cell(state), exec_time)

console.print(table)
console.print(f"Total migrations: {len(rows_data)}  |  Applied: 4  |  Pending: 2  |  Failed: 1")

# ── 7. Migrate: progress bar ─────────────────────────────────────────────────
section("7 / MIGRATE — progress bar  (rich.progress)")

pending = ["V3.2.1__add_payment_method.sql", "V3.2.2__add_fulfilled_at.sql"]

with Progress(
    SpinnerColumn(),
    TextColumn("[progress.description]{task.description}"),
    BarColumn(),
    TaskProgressColumn(),
    TextColumn("[dim]{task.fields[status]}[/dim]"),
    console=console,
    transient=False,
) as progress:
    task = progress.add_task("Applying migrations", total=len(pending), status="")
    for migration in pending:
        progress.update(task, status=f"→ {migration}")
        time.sleep(0.6)
        progress.advance(task)
    progress.update(task, status="done")

console.print()
console.print("[log.notice]NOTICE  2 migrations applied — database is up to date[/log.notice]")

# ── 8. Snapshot / export-schema: status spinner ──────────────────────────────
section("8 / SNAPSHOT — status spinner  (Console.status)")

with console.status("Capturing live schema from db.example.com …", spinner="dots"):
    time.sleep(1.8)
console.print(
    "[log.notice]NOTICE  Snapshot saved to snapshots/myapp_prod_20260430.json[/log.notice]"
)

# ── 9. No-differences diff (green panel) ────────────────────────────────────
section("9 / DIFF — schema in sync (green border)")

clean_panel = Panel(
    "✓ No differences found - schema is in sync",
    title="SCHEMA DIFFERENCES",
    box=box.HEAVY,
    border_style="bold green",
    expand=True,
)
console.print(clean_panel)
ok2_body = Text()
ok2_body.append("Total differences: 0\n")
ok2_body.append("Status: ")
ok2_body.append("SUCCESS", style="bold green")
console.print()
console.print(
    Panel(ok2_body, title="SUMMARY", box=box.HEAVY, border_style="bold green", expand=True)
)

# ── 10. Pretty tracebacks ────────────────────────────────────────────────────
section("10 / PRETTY TRACEBACKS  (install_rich_traceback)")

install_rich_traceback(show_locals=False, word_wrap=False)

try:
    config = {"database": {"host": "db.example.com"}}
    _ = config["database"]["port"]  # KeyError — intentional
except KeyError:
    console.print_exception(show_locals=False)

console.print()
console.print("[bold green]  Demo complete.[/bold green]")
